###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: app-mayikt-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
####swagger相关配置
swagger:
  base-package: com.mayikt.weixin
  title: SpringCloud2.x微信服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”
  version: 1.1
  ####联系网址
  terms-of-service-url: www.baidu.com
  contact:
    name: 易分锐
    email: 1445494883@qq.com